# Generated by Django 5.0.5 on 2024-05-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chotkinarsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='attachments/', verbose_name='Attachment')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chotkinarsa.project', verbose_name='Model that uses the image field')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
