# Generated by Django 5.0.5 on 2024-05-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chotkinarsa', '0002_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='publication',
        ),
        migrations.AddField(
            model_name='attachment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chotkinarsa.project', verbose_name='Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
